"""EV telemetry ingest decoding protobuf with a **Python UDF** instead of ``from_protobuf``.

PySpark counterpart of ``com.aws.emr.spark.iot.SparkProtoUDF``. This is the approach for payloads
that need custom decode logic (a proprietary envelope, conditional parsing, a library the native
connector cannot express); for a plain protobuf message ``from_protobuf`` (see
``iot-native-ingest``) is simpler and much faster - the Python UDF pays a serialization round trip
to Python workers per row.

The protobuf bindings (``iceberg_streaming.proto_gen.VehicleTelemetry_pb2``) are generated by
``scripts/gen_proto.sh``. They are imported lazily inside the UDF so this module imports even before
the bindings have been generated.
"""

from __future__ import annotations

import datetime as _dt
import sys

from pyspark.sql import functions as F
from pyspark.sql.types import (
    BooleanType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from iceberg_streaming.common import DATABASE, JobConfig, Mode
from iceberg_streaming.common.observability import attach_progress_listener
from iceberg_streaming.iot import _telemetry

_TELEMETRY_STRUCT = StructType(
    [
        StructField("vehicle_id", LongType(), True),
        StructField("event_time", TimestampType(), True),
        StructField("model", StringType(), True),
        StructField("speed_kmh", IntegerType(), True),
        StructField("soc_pct", IntegerType(), True),
        StructField("odometer_km", LongType(), True),
        StructField("charging", BooleanType(), True),
    ]
)


def _decode_proto(message_value):
    # Lazy import so the module loads even if the bindings have not been generated yet.
    from iceberg_streaming.proto_gen import VehicleTelemetry_pb2  # type: ignore

    if message_value is None:
        return None
    t = VehicleTelemetry_pb2.VehicleTelemetry()
    t.ParseFromString(bytes(message_value))
    # preserve millisecond precision (seconds + nanos), not just whole seconds
    event_time = _dt.datetime.fromtimestamp(
        t.event_time.seconds + t.event_time.nanos / 1_000_000_000, tz=_dt.timezone.utc
    )
    return (
        int(t.vehicle_id),
        event_time,
        t.model,
        int(t.speed_kmh),
        int(t.soc_pct),
        int(t.odometer_km),
        bool(t.charging),
    )


def main(argv: list[str] | None = None) -> None:
    cfg = JobConfig.from_args(argv if argv is not None else sys.argv[1:])
    spark = cfg.build_session("PySparkTelemetryProtoUDF")

    table = cfg.table(_telemetry.TABLE)
    proto_udf = F.udf(_decode_proto, _TELEMETRY_STRUCT)

    spark.sql(f"CREATE DATABASE IF NOT EXISTS {DATABASE}")
    spark.sql(f"USE {DATABASE}")
    spark.sql(cfg.create_table_ddl(table, _telemetry.COLUMNS_DDL, _telemetry.PARTITION_DDL, Mode.COW))

    df = cfg.kafka_stream(spark, cfg.topic())

    output = df.select(
        proto_udf(F.col("value")).alias("t"),
        F.col("partition").alias("kafka_partition"),
        F.col("offset").alias("kafka_offset"),
    ).select(F.col("t.*"), F.col("kafka_partition"), F.col("kafka_offset"))

    attach_progress_listener(spark)

    query = (
        output.writeStream.queryName(f"proto-udf-ingest-{table}")
        .format("iceberg")
        .trigger(**cfg.trigger_kwargs(60))
        .outputMode("append")
        .option("checkpointLocation", cfg.checkpoint_for(f"proto-udf-ingest-{table}"))
        .option("fanout-enabled", str(cfg.fanout(True)).lower())
        .toTable(table)
    )
    query.awaitTermination()


if __name__ == "__main__":
    main()
