"""Protocol Buffers -> Iceberg v3 using a Python UDF for the decoding.

PySpark counterpart of ``com.aws.emr.proto.SparkProtoUDF``. A pandas/regular UDF parses each Kafka
value into the full ``employee`` struct with the generated protobuf bindings, and the result is
written to an Iceberg v3 table.

The protobuf bindings (``iceberg_streaming.proto_gen.Employee_pb2``) are generated by
``scripts/gen_proto.sh``. They are imported lazily inside the UDF so this module imports even before
the bindings have been generated.
"""

from __future__ import annotations

import datetime as _dt
import sys

from pyspark.sql import functions as F
from pyspark.sql.types import (
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from iceberg_streaming.common import DATABASE, JobConfig

_EMPLOYEE_STRUCT = StructType(
    [
        StructField("employee_id", LongType(), True),
        StructField("age", IntegerType(), True),
        StructField("start_date", TimestampType(), True),
        StructField("team", StringType(), True),
        StructField("role", StringType(), True),
        StructField("address", StringType(), True),
        StructField("name", StringType(), True),
    ]
)

_CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS employee
          (employee_id bigint,
          age int,
          start_date timestamp,
          team string,
          role string,
          address string,
          name string
          )
          PARTITIONED BY (bucket(8, employee_id), hours(start_date), team)
          TBLPROPERTIES (
                    'table_type'='ICEBERG',
                    'format-version'='3',
                    'write.parquet.compression-level'='7',
                    'format'='parquet',
                    'write.parquet.compression-codec'='zstd',
                    'compatibility.snapshot-id-inheritance.enabled'='true' )
"""


def _decode_proto(message_value):
    # Lazy import so the module loads even if the bindings have not been generated yet.
    from iceberg_streaming.proto_gen import Employee_pb2  # type: ignore

    if message_value is None:
        return None
    emp = Employee_pb2.Employee()
    emp.ParseFromString(bytes(message_value))
    role_name = Employee_pb2.Role.Name(emp.role)
    start = _dt.datetime.fromtimestamp(emp.start_date.seconds, tz=_dt.timezone.utc)
    return (
        int(emp.id),
        int(emp.employee_age.value),
        start,
        emp.team.name,
        role_name,
        emp.address,
        emp.name,
    )


def main(argv: list[str] | None = None) -> None:
    cfg = JobConfig.from_args(argv if argv is not None else sys.argv[1:])
    spark = cfg.build_session("PySparkProtoUDF2Iceberg")

    proto_udf = F.udf(_decode_proto, _EMPLOYEE_STRUCT)

    spark.sql(f"CREATE DATABASE IF NOT EXISTS {DATABASE}")
    spark.sql(f"USE {DATABASE}")
    spark.sql(_CREATE_TABLE)

    df = cfg.kafka_stream(spark, "protobuf-demo-topic-pure")

    output = df.select(proto_udf(F.col("value")).alias("employee")).select(F.col("employee.*"))

    query = (
        output.writeStream.queryName("streaming-protobuf-udf-ingest")
        .format("iceberg")
        .trigger(processingTime="1 minute")
        .outputMode("append")
        .option("checkpointLocation", cfg.checkpoint_location)
        .option("fanout-enabled", "true")
        .toTable("employee")
    )
    query.awaitTermination()


if __name__ == "__main__":
    main()
