/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsr.avro.post;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6455443544732514197L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"gsr.avro.post\",\"fields\":[{\"name\":\"employee_id\",\"type\":\"long\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"start_date\",\"type\":\"long\"},{\"name\":\"team\",\"type\":\"string\"},{\"name\":\"role\",\"type\":\"string\"},{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Employee> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Employee to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Employee from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Employee instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long employee_id;
  private int age;
  private long start_date;
  private java.lang.CharSequence team;
  private java.lang.CharSequence role;
  private java.lang.CharSequence address;
  private java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param employee_id The new value for employee_id
   * @param age The new value for age
   * @param start_date The new value for start_date
   * @param team The new value for team
   * @param role The new value for role
   * @param address The new value for address
   * @param name The new value for name
   */
  public Employee(java.lang.Long employee_id, java.lang.Integer age, java.lang.Long start_date, java.lang.CharSequence team, java.lang.CharSequence role, java.lang.CharSequence address, java.lang.CharSequence name) {
    this.employee_id = employee_id;
    this.age = age;
    this.start_date = start_date;
    this.team = team;
    this.role = role;
    this.address = address;
    this.name = name;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return employee_id;
    case 1: return age;
    case 2: return start_date;
    case 3: return team;
    case 4: return role;
    case 5: return address;
    case 6: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: employee_id = (java.lang.Long)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    case 2: start_date = (java.lang.Long)value$; break;
    case 3: team = (java.lang.CharSequence)value$; break;
    case 4: role = (java.lang.CharSequence)value$; break;
    case 5: address = (java.lang.CharSequence)value$; break;
    case 6: name = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'employee_id' field.
   * @return The value of the 'employee_id' field.
   */
  public long getEmployeeId() {
    return employee_id;
  }


  /**
   * Sets the value of the 'employee_id' field.
   * @param value the value to set.
   */
  public void setEmployeeId(long value) {
    this.employee_id = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'start_date' field.
   * @return The value of the 'start_date' field.
   */
  public long getStartDate() {
    return start_date;
  }


  /**
   * Sets the value of the 'start_date' field.
   * @param value the value to set.
   */
  public void setStartDate(long value) {
    this.start_date = value;
  }

  /**
   * Gets the value of the 'team' field.
   * @return The value of the 'team' field.
   */
  public java.lang.CharSequence getTeam() {
    return team;
  }


  /**
   * Sets the value of the 'team' field.
   * @param value the value to set.
   */
  public void setTeam(java.lang.CharSequence value) {
    this.team = value;
  }

  /**
   * Gets the value of the 'role' field.
   * @return The value of the 'role' field.
   */
  public java.lang.CharSequence getRole() {
    return role;
  }


  /**
   * Sets the value of the 'role' field.
   * @param value the value to set.
   */
  public void setRole(java.lang.CharSequence value) {
    this.role = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static gsr.avro.post.Employee.Builder newBuilder() {
    return new gsr.avro.post.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static gsr.avro.post.Employee.Builder newBuilder(gsr.avro.post.Employee.Builder other) {
    if (other == null) {
      return new gsr.avro.post.Employee.Builder();
    } else {
      return new gsr.avro.post.Employee.Builder(other);
    }
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static gsr.avro.post.Employee.Builder newBuilder(gsr.avro.post.Employee other) {
    if (other == null) {
      return new gsr.avro.post.Employee.Builder();
    } else {
      return new gsr.avro.post.Employee.Builder(other);
    }
  }

  /**
   * RecordBuilder for Employee instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private long employee_id;
    private int age;
    private long start_date;
    private java.lang.CharSequence team;
    private java.lang.CharSequence role;
    private java.lang.CharSequence address;
    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gsr.avro.post.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.employee_id)) {
        this.employee_id = data().deepCopy(fields()[0].schema(), other.employee_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.start_date)) {
        this.start_date = data().deepCopy(fields()[2].schema(), other.start_date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.team)) {
        this.team = data().deepCopy(fields()[3].schema(), other.team);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.role)) {
        this.role = data().deepCopy(fields()[4].schema(), other.role);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.address)) {
        this.address = data().deepCopy(fields()[5].schema(), other.address);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.name)) {
        this.name = data().deepCopy(fields()[6].schema(), other.name);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(gsr.avro.post.Employee other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.employee_id)) {
        this.employee_id = data().deepCopy(fields()[0].schema(), other.employee_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.start_date)) {
        this.start_date = data().deepCopy(fields()[2].schema(), other.start_date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.team)) {
        this.team = data().deepCopy(fields()[3].schema(), other.team);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.role)) {
        this.role = data().deepCopy(fields()[4].schema(), other.role);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.address)) {
        this.address = data().deepCopy(fields()[5].schema(), other.address);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.name)) {
        this.name = data().deepCopy(fields()[6].schema(), other.name);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'employee_id' field.
      * @return The value.
      */
    public long getEmployeeId() {
      return employee_id;
    }


    /**
      * Sets the value of the 'employee_id' field.
      * @param value The value of 'employee_id'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setEmployeeId(long value) {
      validate(fields()[0], value);
      this.employee_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'employee_id' field has been set.
      * @return True if the 'employee_id' field has been set, false otherwise.
      */
    public boolean hasEmployeeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'employee_id' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearEmployeeId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setAge(int value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearAge() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'start_date' field.
      * @return The value.
      */
    public long getStartDate() {
      return start_date;
    }


    /**
      * Sets the value of the 'start_date' field.
      * @param value The value of 'start_date'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setStartDate(long value) {
      validate(fields()[2], value);
      this.start_date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'start_date' field has been set.
      * @return True if the 'start_date' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'start_date' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearStartDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'team' field.
      * @return The value.
      */
    public java.lang.CharSequence getTeam() {
      return team;
    }


    /**
      * Sets the value of the 'team' field.
      * @param value The value of 'team'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setTeam(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.team = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'team' field has been set.
      * @return True if the 'team' field has been set, false otherwise.
      */
    public boolean hasTeam() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'team' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearTeam() {
      team = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'role' field.
      * @return The value.
      */
    public java.lang.CharSequence getRole() {
      return role;
    }


    /**
      * Sets the value of the 'role' field.
      * @param value The value of 'role'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setRole(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.role = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'role' field has been set.
      * @return True if the 'role' field has been set, false otherwise.
      */
    public boolean hasRole() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'role' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearRole() {
      role = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.address = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearAddress() {
      address = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder setName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.name = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public gsr.avro.post.Employee.Builder clearName() {
      name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.employee_id = fieldSetFlags()[0] ? this.employee_id : (java.lang.Long) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        record.start_date = fieldSetFlags()[2] ? this.start_date : (java.lang.Long) defaultValue(fields()[2]);
        record.team = fieldSetFlags()[3] ? this.team : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.role = fieldSetFlags()[4] ? this.role : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.address = fieldSetFlags()[5] ? this.address : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.name = fieldSetFlags()[6] ? this.name : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.employee_id);

    out.writeInt(this.age);

    out.writeLong(this.start_date);

    out.writeString(this.team);

    out.writeString(this.role);

    out.writeString(this.address);

    out.writeString(this.name);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.employee_id = in.readLong();

      this.age = in.readInt();

      this.start_date = in.readLong();

      this.team = in.readString(this.team instanceof Utf8 ? (Utf8)this.team : null);

      this.role = in.readString(this.role instanceof Utf8 ? (Utf8)this.role : null);

      this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.employee_id = in.readLong();
          break;

        case 1:
          this.age = in.readInt();
          break;

        case 2:
          this.start_date = in.readLong();
          break;

        case 3:
          this.team = in.readString(this.team instanceof Utf8 ? (Utf8)this.team : null);
          break;

        case 4:
          this.role = in.readString(this.role instanceof Utf8 ? (Utf8)this.role : null);
          break;

        case 5:
          this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);
          break;

        case 6:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










